### ISSUE TITLE
Make card in loop

### ISSUE THREAD

**Issue by ShayanSolution** [konstantingassmann/cardslider#1]
How can i change library so it shows card in loop, one swiped card gets back on stack and loop continues

**Comment by konstantingassmann** [comment]
Hi,
this feature isn't yet implemented, but it's on my schedule.
I will implement it in near future and notify you when it's available.

Cheers
Konstantin

**Comment by konstantingassmann** [comment]
Hi @arslan,
i've added the capability to loop the cards in v1.1.0.

Let me know if you have some other problems or ideas.

Cheers
Konstantin
