### ISSUE TITLE
Where do i edit actual card slide content?

### ISSUE THREAD

**Issue by VanillaTiger** [konstantingassmann/cardslider#2]
Hi I am trying to add edit content of the card slider. I added div and styles within <li>this is card 2</li> but cannot actually create background and build/control content within the card.

**Comment by konstantingassmann** [comment]
Hi @VanilaTiger just add your Content inside the li elements. Initially the cards are white so you may not see them if your background is white too. I hope this helps.

**Comment by VanillaTiger** [comment]
Write i get there you do it in LI, but if im trying to actually impact it by changing background of all card object not only text,<li> inside i am not able.

I guess its because in your js script you are assigning different background to cards with some grayscale. Therefore when i am trying to give some photo as a background it does not pick it up

am i correct?

**Comment by VanillaTiger** [comment]
haha it edited my text <*li> instead of dot

**Comment by konstantingassmann** [comment]
Hi,
yes the cards get a background assigned. This happens through some classes.
The default background is assigned by the class `.cardslider__card`
For the first to fourth card there are the classes `.cardslider__card--index-0`, `.cardslider__card--index-1`,...`.cardslider__card--index-3` which set the background from white to gray. you can change this by overwriting these classes.
The last class which is doning something with the background is `.cardslider__card--transitions` this transitions the background from light to dark or dark to light. By overwriting this class you can change this behaviour.

I hope this helps. All changes are made with css and are never applied directly to the element by javascript so you should be able to change this easily
cheers

**Comment by powierski** [comment]
Hi, is there a way to only show a specific number of cards in the stack at one time? Maybe 3 or 4 cards?
