### ISSUE TITLE
Display a specific number of cards

### ISSUE THREAD

**Issue by powierski** [konstantingassmann/cardslider#3]
Hi, is there a way to only show a specific number of cards in the stack at one time? For example I might have 40 cards in total but don't want them all visible in the stack, I'd maybe want to show 3 or 4 cards at any one time?

**Comment by konstantingassmann** [comment]
Hi,
this is not possible at the moment, but i will put it on the feature list.

**Comment by powierski** [comment]
Thanks, I've just used css for now to hide the other cards which is fine but would be nice to be able to specify it in slider options.

**Comment by konstantingassmann** [comment]
HI @powierski,
I've added this feature in v1.2.0
Thanks for using the plugin
