### ISSUE TITLE
Embedding list items in card

### ISSUE THREAD

**Issue by diolov** [konstantingassmann/cardslider#4]
I have the card content be populated via CMS backend, and sometimes when users use lists (ordered, or unordered) they get cards within cards because the JS selector grabs all "li" elements inside the "cardslider" element.

I've modified the js to fix this issue by updating the card selector query
`var rawcards = list.children;`

**Comment by konstantingassmann** [comment]
Hi diolov,
thanks for using cardslider.
I will fix it asap.

Cheers
Konstantin

**Comment by konstantingassmann** [comment]
Hi diolov,
the Bug is fixed in version 1.1.3
